export const STORAGES = {
  ACCESS_TOKEN: 'WEBSITE_ACCESS_TOKEN',
  REFRESH_TOKEN: 'WEBSITE_REFRESH_TOKEN',
  USER_LOGIN: 'WEBSITE_USER_LOGIN',
  VERSION_LOADING: 'WEBSITE_VERSION_LOADING',
  LANGUAGE: "WEBSITE_LANGUAGE",
  OTP_DEADLINE: "WEBSITE_OTP_DEADLINE"
};
